name: Keehn Consulting
favicon: null
layout_spectrum: 0.5025191202294081
typography_spectrum: 0.41598314815200865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07461750344373286
  lightness: 0.4315260050352663
  saturation: 0.30007599317468703
  rhythmicContrast: 0.27421216177754104
purpose: []
